resource_types:
- name: redis
  type: docker-image
  source:
    repository: benmoss/concourse-redis-resource

resources:
- name: numbers
  type: redis
  source:
    host: 192.168.0.2
    port: 6379
    key: numbers
- name: numbers
  type: redis
  source:
    host: 192.168.0.2
    port: 6379
    key: primes
- name: tick
  type: time
  source: {interval: 10s}
- name: scripts
  uri: https://github.com/benmoss/redis-resource.git
  branch: master

jobs:
- name: increment
  serial: true
  plan:
    - get: tick
      trigger: true
    - get: numbers
    - task: inc
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: alpine
            tag: latest
        inputs: [name: numbers]
        outputs: [name: output]
        run:
          path: /bin/sh
          args: [-c, set -ex; expr $(cat ./numbers/value) + 1 > output/stuff || true]
    - put: numbers
      params:
        file: output/stuff

- name: find-primes
  serial: true
  plan:
    - get: scripts
    - get: numbers
      trigger: true
    - task: is-prime
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: ruby
            tag: 2.1
        inputs: [name: numbers]
        outputs: [name: output]
        run:
          path: /bin/sh
    - put: numbers
      params:
        file: scripts/scripts/is_prime.rb

- name: put-a-zero
  plan:
    - task: foo
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: alpine
            tag: latest
        outputs: [name: output]
        run:
          path: /bin/sh
          args: [-c, "set -ex; echo 0 > ./output/stuff"]
    - put: numbers
      params:
        file: output/stuff
