#!/bin/bash
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

payload=$TMPDIR/redis-resource-request
cat > $payload <&0

host=$(jq -r '.source.host // ""' < $payload)
port=$(jq -r '.source.port // ""' < $payload)
key=$(jq -r '.source.key // ""' < $payload)
ref=$(jq -r '.version.ref // ""' < $payload)


if [ -n "$ref" ]; then
  results=$(redis-cli --raw -h $host -p $port lrange $key 0 -1 | sed "/$ref/q") 
else
  results=$(redis-cli --raw -h $host -p $port lrange $key 0 0)
fi

if [ -n "$results" ]; then
  echo "$results" | jq -R "." | jq -s "map({ref: .})" >&3
else
  echo [] >&3
fi
