#!/bin/bash
# vim: set ft=sh

set -ex

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

destination=$1

payload=$(mktemp $TMPDIR/redis-resource-request.XXXXXX)
cat > $payload <&0

host=$(jq -r '.source.host // ""' < $payload)
port=$(jq -r '.source.port // ""' < $payload)
key=$(jq -r '.source.key // ""' < $payload)
ref=$(jq -r '.version.ref // ""' < $payload)

redis() {
  redis-cli --raw -h $host -p $port "$@"
}
if [ -z "$ref" ]; then
  echo "no ref provided"
  exit 1
fi

cd $destination
value=$(redis hget "$key-h" $ref)

echo $value > value

jq -n "{
  version: {ref: $(echo $ref | jq -R .)},
  metadata: [{name: \"value\", value: $(echo $value | jq -R .)}]
}" >&3
